### ISSUE TITLE
new build + block_X vs tilesize_X

### ISSUE THREAD

**Issue by Selur** [Kiyamou/VapourSynth-SRMD-ncnn-Vulkan#1]
a new build/release would be nice
instead of
"block_w:int:opt;"
"block_h:int:opt;"
tilesize_x and tilesize_y should be used as parameter names for consistency

**Comment by Kiyamou** [comment]
It's a good idea. I will do it tomorrow.

**Comment by Kiyamou** [comment]
Already updated and release [new build version](https://github.com/Kiyamou/VapourSynth-SRMD-ncnn-Vulkan/releases/tag/r2).

**Comment by Kiyamou** [comment]
It seems normal. So I close the issue.
If any problems, please reopen it. : )
