### ISSUE TITLE
how to run this command

### ISSUE THREAD

**Issue by Gavin-zsr** [Kiyamou/VapourSynth-SRMD-ncnn-Vulkan#3]
After I build this repo, I don't know how to run this command
 `core.srmdnv.SRMD(clip clip, [int scale, int noise, int tilesize_x, int tilesize_y, int gpu_id, int gpu_thread, bool tta])`
I don't know what's the clip means? A picture name or something else?
If I run like this `core.srmdnv.SRMD('test.jpg', scale=2)`  it will prompt a syntax error `syntax error near unexpected token `test.jpg'`
Could you please provide a example command for me. Thank you!

**Comment by Kiyamou** [comment]
It is not command, while it is python code.

The repo is a plugin for [VapourSynth frame](http://www.vapoursynth.com/). If you want to use it, there are something to to.
* 0.Firstly, VapourSynth use python as front end, you just need to use it like python.
* 1.Install VapourSynth, and the IDE, [vseditor](https://bitbucket.org/mystery_keeper/vapoursynth-editor/src/master/).
* 2.Prepare necessary plugins and python scripts, such as mvsfunc and fmtconv. You can find them in github.

  * python scripts should be at Python's `site-packages`, like other python packages which installed by pip (such as mvsfunc).
  * plugins should be at VapourSynth's directory, including the repo and other plugins (such as fmtconv).
    * For windows, the directory may be `C:\Program Files\VapourSynth\plugins`
    * For linux, the directory may be `usr/local/vapoursynth`

* 3.Write a piece of python, like this follow.
```python
import vapoursynth as vs
import mvsfunc as mvf
core = vs.get_core()

src = core.imwri.Read("test.jpg") # import image
src = mvf.Depth(src, 32) # change format to 32bit float, mvsfunc need the plugin, fmtconv.
src = core.srmdnv.SRMD(src, scale=2)

src.set_output() # output
```
* 4.Debug in IDE, you can get the processed image in preveiw window. if you only want to process single image, not video, IDE is enough.

This is a simple example. If you want to process video, maybe need more pre-processing, and need encoder.

In addition, "clip" is just an idiom. You can think it as input. In fact, "clip" is meaning as video clip. Of course, you can use `core.imwri.Read` to import single image, too.

**Comment by Gavin-zsr** [comment]
OK, I have known how to use this repo. Thank you for your detatil explanation.
